### ISSUE TITLE
Banner Ads

### ISSUE THREAD

**Issue by jbolan28** [byrobingames/unityads#1]
The banner test ads aren't showing.  I created the necessary banner ad on Unity, then within my game I checked if they were available then showed them at the bottom of the screen yet nothing occurs. 

I tested if they would show without the if statement and played around with the move to bottom/top block with no luck.

**Comment by byrobin81** [comment]
On wich platform??  Android or IOS.

Can you share some logs?

Thanks..

**Comment by byrobingames** [comment]
On wich platform?? Android or IOS.

Can you share some logs?

Are you on Stencyl3.4 or 3.5

**Comment by jbolan28** [comment]
I'm testing on iOS, using build 10134 which would be Stencyl 3.5.
[log-2018-12-28.zip](https://github.com/byrobingames/unityads/files/2715949/log-2018-12-28.zip)

**Comment by byrobingames** [comment]
Ok i am on the same build and no problems on my side... and I can not see anything In the logs.

Is it possible to share your gameid and placement id with me so I an test it on my side. (you can mail It to me if your want info@byrobin.nl)

**Comment by byrobingames** [comment]
i am gonna close this issue.
