### ISSUE TITLE
Don't compile android after stencyl update

### ISSUE THREAD

**Issue by rodolfovs** [byrobingames/unityads#4]
Hi Robin,

I updated Stencyl to version 10458 and the UnityAds extension has stopped working, I can no longer test the game on android device, appears the error  below:

> stencyl.sw.util.StreamGobbler	[haxelib] * Get more help at https://help.gradle.org
stencyl.sw.util.StreamGobbler	[haxelib] Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
stencyl.sw.util.StreamGobbler	[haxelib] * Try:
stencyl.sw.util.StreamGobbler	[haxelib]          project :deps:unityads
stencyl.sw.util.StreamGobbler	[haxelib]      Required by:
stencyl.sw.util.StreamGobbler	[haxelib]        - http://repo1.maven.org/maven2/com/android/tools/build/gradle/3.5.1/gradle-3.5.1.jar
stencyl.sw.util.StreamGobbler	[haxelib]        - http://repo1.maven.org/maven2/com/android/tools/build/gradle/3.5.1/gradle-3.5.1.pom
stencyl.sw.util.StreamGobbler	[haxelib]      Searched in the following locations:
stencyl.sw.util.StreamGobbler	[haxelib]    > Could not find com.android.tools.build:gradle:3.5.1.
stencyl.sw.util.StreamGobbler	[haxelib] > Could not resolve all artifacts for configuration ':deps:unityads:classpath'.
stencyl.sw.util.StreamGobbler	[haxelib] A problem occurred configuring project ':deps:unityads'.
stencyl.sw.util.StreamGobbler	[haxelib] * What went wrong:
stencyl.sw.util.StreamGobbler	[haxelib] FAILURE: Build failed with an exception.

Do I need to update anything else for the extension to work again?

**Comment by byrobingames** [comment]
All extensions needs a update to work with gradle 3.5.1

You can do it your self by follow this link.

https://github.com/byrobingames/byRobinextensionmanager/issues/2#issuecomment-554739604

I am updating extensions in upcoming weeks..

**Comment by rodolfovs** [comment]
Hi Robin,

I already made the change and everything worked out, thanks.
